---
title: "International Travel Bans Policies in the COVID-19 pandemic year 2020"
author: "Thuy Nguyen"
date: "12/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(tidyverse)
library(dplyr)
library(janitor)
library(lubridate)
library(ggplot2)

# https://dataverse.harvard.edu/dataverse/COVIDBorderAccountabilityProjectCOBAP downloaded March 15, 2021

d <- rio::import(here::here("data", "policy_list.csv")) %>% 
  select(-c(23)) %>% 
  janitor::clean_names() %>% 
  filter(country_name != "Norfolk Island") 


data <- d %>% 
  mutate(start_asdate = lubridate::mdy(d$start_date), # date format mm_dd_yyyy
         end_asdate = lubridate::mdy(d$end_date)) %>% 
  select(c(country_name, iso3, policy_type, air, land, sea, start_asdate, end_asdate))
```

```{r number of border close policies}
# data for the line chart
 pd_line <- data %>% 
  #count in week interval
  select(country_name, iso3, start_asdate) %>% 
  add_count(week = floor_date(start_asdate, "week")) %>% 
  arrange(start_asdate) %>% 
  drop_na()

nrow(pd_line) 
head(pd_line)

pd_line %>% 
  top_n(n, 10)

```

```{r}

# plot
  p <- pd_line %>% 
  ggplot(aes(week, n)) +

  geom_vline(xintercept = as.Date("2020-03-11"), linetype = "dotted", color = "#780A0B") +
   geom_text(label = "Pandemic declared (March 11)", 
             size = 3, color = "#780A0B", hjust = -0.5,
             x = as.Date("2020-02-26"), # arbitrary date to make sure the text does not cross the vline
             y = 250
            ) + 
  geom_point(aes(week, n), size = 6, shape = 21, fill = "#3E80B6", color = "#3E80B6") +

  geom_line(color = "#3E80B6", size = 1) +
  
  #show values inside the points
  geom_text(aes(label = n),
            color = "white",
            size = 3) + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b %d") +
  labs(x = "",
       y = "",
       title = "", 
       subtitle = "",
       caption = "") + 
  theme_light() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank()
  )
p
```

```{r, fig.width= 11, fig.width=9}
num_ban <- p + 
        # North Korea; 
    annotate(geom = "text", 
                 x = as.Date("2020-01-22"), 
                 y = .5,
                label = "North\nKorea", vjust = -2, hjust = 0.9, color = "#3E80B6") +
                
    annotate("segment", x = as.Date("2020-01-20"), xend = as.Date("2020-01-20"), # arbitrary date
               y = 50, yend = 3, colour = "#3E80B6", size=.5, alpha = .5) +   
  
  # the second week:  Mozambique, Viet Nam, Singapore, Georgia, Dominica, Israel, Guatemala, Italy, Pakistan, Russia, Kiribati, Kyrgyzstan, Palau
 
  annotate(geom = "text", 
                 x = as.Date("2020-01-26"), 
                 y = .5,
                label = "Mozambique\nViet Nam\nSingapore\nGeorgia\nDominica\nIsrael\nGuatemala\nItaly\nPakistan\nRussia\nKiribati\nKyrgyzstan\nPalau", vjust = - 0.8, hjust = 0, color = "#3E80B6") +
                
    annotate("segment", x = as.Date("2020-01-26"), xend = as.Date("2020-01-26"), 
               y = 360, yend = 10, colour = "#3E80B6", size=.5, alpha = .5) 
 num_ban
 
 # ggsave("num_ban.png", num_ban, width = 11, height = 9, units = "in")
```

## Countries with high number of border close policies issued 

There were 21 countries that issued more than 10 border close policies. 

```{r lolitop}
library(forcats)
# countries issued more than 10 policies

top10policies <- data %>% 
  group_by(country_name) %>% 
  count() %>% 
  filter(n > 10) %>% 
  mutate(country_name = forcats::fct_reorder(country_name, n)) %>% 
  ggplot(aes(country_name, n)) +
  geom_segment(aes(x = country_name, xend = country_name, y = 0, yend = n), color = "skyblue") +
  geom_point(color = "orange", size = 3) +
  labs(
    title = "Countries issued more than 10 border close policies",
    x = "",
    y = "",
    caption = "Source: Covid Border Accountability Project (COBAP)"
  ) +
  theme_light() +
  coord_flip() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.border = element_blank(),
    axis.ticks.y = element_blank()
  )
```

## Complete vs partial policies 1

```{r}
complete_data <- data %>% 
  #count in week interval
  filter(policy_type == "COMPLETE") %>% 
  select(policy_type, country_name, iso3, start_asdate) %>% 
  add_count(week = floor_date(start_asdate, "week")) %>% 
  arrange(start_asdate) %>% 
  drop_na()

partial_data <- data %>% 
  #count in week interval
  filter(policy_type == "PARTIAL") %>% 
  select(policy_type, country_name, iso3, start_asdate) %>% 
  add_count(week = floor_date(start_asdate, "week")) %>% 
  arrange(start_asdate) %>% 
  drop_na()

p_complete_partial1 <- complete_data %>% 
  ggplot(aes(week, n)) +
   # Pandemic line
  geom_vline(xintercept = as.Date("2020-03-11"), linetype = "dotted", color = "#780A0B") +
   geom_text(label = "Pandemic declared (March 11)", 
             size = 3, color = "#780A0B", hjust = -0.3,
             x = as.Date("2020-02-26"), # arbitrary date to make sure the text does not cross the vline
             y = 250
            ) + 
  geom_line(color = "#A8DBD9", size = 1)+
  geom_point(aes(week, n), size = 6, shape = 21, fill = "#A8DBD9", color = "#A8DBD9") +
    #show values inside the point
  geom_text(aes(label = n),
            color = "white",
            size = 3) +
  # show values of partial 
  geom_line(data = partial_data, color = "#FFC6C4", size = 1)+
   
  scale_x_date(date_breaks = "1 month", date_labels = "%b %d") +
  labs(x = "",
       y = "",
       title = "", 
       subtitle = "",
       caption = "") + 
  theme_light() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.border = element_blank()
  )

p_complete_partial1
```

```{r}
library(treemap)
pd_treemap <- data %>% 
  #select(country_name, policy_type) %>% 
  group_by(policy_type) %>% 
  unique() %>% 
  add_count() 

treemap(
  pd_treemap,
  index = "policy_type",
  vSize = "n",
  type = "index",
  title="Policy type",
  fontcolor.labels=c("white"),
  palette = "Set2",
  border.col=c("white") # can add more border color
)


group <- c(rep("Complete closure",1), rep("Partial closure", 4))
subgroup <- c(rep("Complete closure",1), rep("Border closure", 3), rep("Targeted ban", 1))
subsubgroup <- c(rep("Complete closure",1), "Air", "Land", "Sea", "Targeted ban")
value <- c(410, 100, 100, 100, 200)
data_treemap <- data.frame(group,subgroup, subsubgroup,value)

p_treemap <- treemap(data_treemap,
            index=c("group","subgroup", "subsubgroup"),
            vSize="value",
            type="index",
            palette = "Set2",
            bg.labels=c("white"),
            align.labels=list(
              c("center", "center"), 
              c("right", "bottom")
            )  
          )    
```


### Who targets whom

```{r table of who targets whom}
library(gt)
table <- d %>% 
select(country_name, targets_air, targets_land, targets_sea) %>% 
  drop_na() %>% 
  filter(targets_air != "NA") %>% 
  rename("Country" = country_name,
         "Air" = targets_air,
         "Land" = targets_land,
         "Sea" = targets_sea) 
reactable::reactable(table)
```

